name: Deploy Snowpark

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Specify the deployment environment (dev or prod)"
        required: true
        default: "dev"

env:
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: "account"
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER: "user"
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_SCHEMA: "ml"
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_WAREHOUSE: "xsmall"
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_ROLE: "rss"
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_PRIVATE_KEY: "key"
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_AUTHENTICATOR: "SNOWFLAKE_JWT"

jobs:
  cancel:
    name: Cancel Previous Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Cancel runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          ignore_sha: true

  deploy-dev:
    if: github.event.inputs.tags == 'dev' || github.event.inputs.tags == 'PROD'
    name: Deploy DEV
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE: "dev"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Print environment variables (DEV)
        run: |
          echo "Printing environment variables for DEV deployment:"
          echo "SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT=$SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT"
          echo "SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER=$SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER"
          echo "SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE=$SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE"
          echo "SNOWFLAKE_CONNECTIONS_MYCONNECTION_SCHEMA=$SNOWFLAKE_CONNECTIONS_MYCONNECTION_SCHEMA"
          echo "SNOWFLAKE_CONNECTIONS_MYCONNECTION_WAREHOUSE=$SNOWFLAKE_CONNECTIONS_MYCONNECTION_WAREHOUSE"
          echo "SNOWFLAKE_CONNECTIONS_MYCONNECTION_ROLE=$SNOWFLAKE_CONNECTIONS_MYCONNECTION_ROLE"
          echo "SNOWFLAKE_CONNECTIONS_MYCONNECTION_PRIVATE_KEY=$SNOWFLAKE_CONNECTIONS_MYCONNECTION_PRIVATE_KEY"
          echo "SNOWFLAKE_CONNECTIONS_MYCONNECTION_AUTHENTICATOR=$SNOWFLAKE_CONNECTIONS_MYCONNECTION_AUTHENTICATOR"
          # Add more echo statements for other variables if needed
          
      # Add more steps for DEV deployment here

  deploy-prod:
    if: github.event.inputs.tags == 'prod'
    name: Deploy PROD
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE: "prod"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Print environment variables (PROD)
        run: |
          echo "Printing environment variables for PROD deployment:"
          echo "SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT=$SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT"
          echo "SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER=$SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER"
          echo "SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE=$SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE"
          echo "SNOWFLAKE_CONNECTIONS_MYCONNECTION_SCHEMA=$SNOWFLAKE_CONNECTIONS_MYCONNECTION_SCHEMA"
          echo "SNOWFLAKE_CONNECTIONS_MYCONNECTION_WAREHOUSE=$SNOWFLAKE_CONNECTIONS_MYCONNECTION_WAREHOUSE"
          echo "SNOWFLAKE_CONNECTIONS_MYCONNECTION_ROLE=$SNOWFLAKE_CONNECTIONS_MYCONNECTION_ROLE"
          echo "SNOWFLAKE_CONNECTIONS_MYCONNECTION_PRIVATE_KEY=$SNOWFLAKE_CONNECTIONS_MYCONNECTION_PRIVATE_KEY"
          echo "SNOWFLAKE_CONNECTIONS_MYCONNECTION_AUTHENTICATOR=$SNOWFLAKE_CONNECTIONS_MYCONNECTION_AUTHENTICATOR"
          # Add more echo statements for other variables if needed
          
      # Add more steps for PROD deployment here
