name: Deploy Snowpark

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Specify the deployment environment (DEV or PROD)"
        required: true
        default: "DEV"

env:
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: "account"
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER: "user"
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_SCHEMA: "ml"
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_WAREHOUSE: "xsmall"
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_ROLE: "rss"
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_PRIVATE_KEY: "key"
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_AUTHENTICATOR: "SNOWFLAKE_JWT"

jobs:
  cancel:
    name: Cancel Previous Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Cancel runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          ignore_sha: true

  deploy-dev:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'DEV' || github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    name: Deploy DEV
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE: "RSS_DEV"
    
    steps:
      - name: Echo environment
        run: echo "Deploying to DEV environment"

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Print environment variables (DEV)
        run: |
          echo "Printing environment variables for DEV deployment:"
          echo "SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE=$SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE" 

      # Snowflake CLI installation
      - uses: Snowflake-Labs/snowflake-cli-action@v1
        with:
          cli-version: "latest"
            # default-config-file-path: "config.toml"
        
      # Use the CLI
      - name: Deploy Snowpark apps
        run: |
           snow --version
           snow connection list

  deploy-prod:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'PROD' }}
    name: Deploy PROD
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE: "RSS_PROD"
    steps:
      - name: Echo environment
        run: echo "Deploying to PROD environment"

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Print environment variables (PROD)
        run: |
          echo "Printing environment variables for PROD deployment:"
          echo "SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE=$SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE"

      # Snowflake CLI installation
      - uses: Snowflake-Labs/snowflake-cli-action@v1
        with:
          cli-version: "latest"
            # default-config-file-path: "config.toml"
        
      # Use the CLI
      - name: Deploy Snowpark apps
        run: |
           snow --version
           snow connection list
