name: Deploy Snowpark

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Specify the deployment environment (dev or prod)"
        required: true
        default: "dev"

jobs:
  cancel:
    name: Cancel Previous Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Cancel runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          ignore_sha: true

  deploy-dev:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev' || github.ref == 'refs/heads/main' }}
    name: Deploy DEV
    runs-on: ubuntu-latest
    steps:
      - name: Echo environment
        run: echo "Deploying to DEV environment"

  deploy-prod:
    if: ${{ github.event.inputs.environment == 'prod' }}
    name: Deploy PROD
    runs-on: ubuntu-latest
    steps:
      - name: Echo environment
        run: echo "Deploying to PROD environment"
